# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Checkmarx CxFlow Action
        uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.1
        with:
          checkmarx_url: ${CHECKMARX.URL}
          team: ${CHECKMARX.TEAM}
          checkmarx_username: ${CHECKMARX.SAST_USERNAME}
          checkmarx_password: ${CHECKMARX.SAST_PASSWORD}
          checkmarx_client_secret: ${CHECKMARX.CLIENT_SECRET}
          project: ${CHECKMARX.PROJECT}
          app: ${CHECKMARX.APP}
          preset: ${CHECKMARX.PRESET}
          break_build: false
          bug_tracker: Sarif
          incremental: false
          params: ${CHECKMARX.SCA_PARAMS}
          github_token: ${github.token}
          scanners: sast, sca
          sca_api_url: https://api.scacheckmarx.com
          sca_app_url: https://sca.scacheckmarx.com
          sca_access_control_url: https://platform.checkmarx.net
          sca_tenant: SCA
          sca_username: ${CHECKMARX.SCA_USERNAME}
          sca_password: ${CHECKMARX.SCA_PASSWORD}
          
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
